package com.github.avrilfanomar.picatplugin.language.lexer

import com.intellij.lexer.GeneratedLexerAdapter
import com.intellij.lexer.FlexAdapter // It might be a FlexAdapter if the generated lexer is a .flex file

// Assuming the generated lexer is _PicatLexer and is in the psi package or a sub-package.
// The exact package and name of _PicatLexer needs to be verified if this fails.
// It might be com.github.avrilfanomar.picatplugin.language.psi._PicatLexer
// or com.github.avrilfanomar.picatplugin.language.parser._PicatLexer
// For now, let's try the psi package as per typical GrammarKit generation structure.
// If _PicatLexer is a JFlex lexer, it would be wrapped by a specific adapter.
// The GrammarKit plugin should generate a class like _PicatLexer which might itself be an adapter or need one.
// Let's assume _PicatLexer is the class generated by GrammarKit that needs to be adapted.
// The constructor _PicatLexer(null) is typical for JFlex-based lexers.
// If GrammarKit generates a plain JFlex file (_PicatLexer.flex), then we might need to use new FlexAdapter(new _PicatLexer(null))
// Let's try with the assumption that _PicatLexer is a class ready to be passed to GeneratedLexerAdapter.
// The actual generated lexer class is often found in a 'parser' sub-package of the main psi package, or directly in the psi package.
// Example path based on BNF: com.github.avrilfanomar.picatplugin.language.psi._PicatLexer
// If the generated lexer is directly usable, it might be:
// class PicatLexerAdapter : GeneratedLexerAdapter(com.github.avrilfanomar.picatplugin.language.psi._PicatLexer(null))
// Let's try to find it in the default parser package that Grammar-Kit might create based on the psiPackage.
// The task `generateLexer` in GrammarKit generates a Java file (e.g., _PicatLexer.java).
// This generated class is then compiled.
// The typical usage is to wrap this generated lexer.
// Let's assume the generated class is `_PicatLexer` and it's located in `com.github.avrilfanomar.picatplugin.language.parser`.
class PicatLexerAdapter : GeneratedLexerAdapter(com.github.avrilfanomar.picatplugin.language.parser._PicatLexer(null))
